- name: Deploy a web application
  hosts: db_and_webserver1,db_and_web_server2
  tasks:
    - name: Install all required dependencies
      apt: name {{ item }} state=present force=yes
      with_items: 
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
    - include: tasks/deploy_db.yaml
    - include: tasks/deploy_web.yaml