# Installing Python Flask repository on the server
- name: Install Python Flask repository
  pip:
    name: "{{ item }}"
    state: present 
  with_items:
    - flask
    - flask-mysql

# Copy the source code
- name: Copy source code
  copy: src=app.py dest=/opt/app/py

# Starting the services
- name: Start Web Server 
  shell: FLASK_APP=/opt/app.py nohup flask run ---host=0.0.0.0 &